### PR TITLE
new payloads

### PR DESCRIPTION
**Pull request by kleo**
minor changes to wallpaper-prank

### CODE REVIEW

**Comment by B3H1NDu** [comment]
Please follow the MIT license under which these payloads were originally released and give full credit to all contributors. Trying to pass others original ideas/work as your own is not nice.

**Comment by kbeflo** [comment]
I understand

**Comment by kleo** [comment]
I stand corrected for passing payloads without credit. I thought it was okay, because it didn't come from a repository.

**Comment by B3H1NDu** [comment]
It's fine.

**Pull request closed without merging**
